package dev.langchain4j.guardrail;

import dev.langchain4j.data.message.AiMessage;
import java.util.Arrays;

/**
 * An output guardrail is a rule that is applied to the output of the model to ensure that the output is safe and meets
 * the expectations.
 * <p>
 * In the case of reprompting, the reprompt message is added to the LLM context and the request is retried.
 * <p>
 * The maximum number of retries is configurable, defaulting to {@link dev.langchain4j.guardrail.config.OutputGuardrailsConfig#MAX_RETRIES_DEFAULT}.
 */
/**
 * 输出护栏是应用于模型输出的规则，用于确保模型输出安全且符合预期要求。
 * <p>
 * 在重新提示（reprompting）场景下，重新提示消息会被添加到 LLM 上下文，并重新发起请求。
 * <p>
 * 最大重试次数可配置，默认值为 {@link dev.langchain4j.guardrail.config.OutputGuardrailsConfig#MAX_RETRIES_DEFAULT}。
 */
public interface OutputGuardrail extends Guardrail<OutputGuardrailRequest, OutputGuardrailResult> {
    /**
     * Validates the response from the LLM.
     * 校验大语言模型（LLM）返回的响应结果。
     *
     * @param responseFromLLM
     *            the response from the LLM
     */
    default OutputGuardrailResult validate(AiMessage responseFromLLM) {
        return failure("Validation not implemented");
    }

    /**
     * Validates the response from the LLM.
     * <p>
     * Unlike {@link #validate(AiMessage)}, this method allows you to access the memory and the augmentation result (in the
     * case of a RAG).
     * <p>
     * Implementation must not attempt to write to the memory or the augmentation result.
     *
     * @param request
     *            the parameters, including the response from the LLM, the memory, and the augmentation result.
     */
    /**
     * 校验大语言模型（LLM）返回的响应结果。
     * <p>
     * 与 {@link #validate(AiMessage)} 不同，此方法可以访问对话记忆（memory）和增强结果（augmentation result），
     * 适用于 RAG（检索增强生成）场景。
     * <p>
     * 实现类**不得**尝试修改记忆体或增强结果。
     *
     * @param request 校验参数，包含模型响应、对话记忆以及增强结果
     */
    @Override
    default OutputGuardrailResult validate(OutputGuardrailRequest request) {
        return validate(request.responseFromLLM().aiMessage());
    }

    /**
     * Produces a successful result without any successful text
     *
     * @return The result of a successful output guardrail validation.
     */
    /**
     * 生成一个不携带任何成功文本的成功结果
     *
     * @return 输出护栏校验通过的结果
     */
    default OutputGuardrailResult success() {
        return OutputGuardrailResult.success();
    }

    /**
     * Produces a successful result with specific success text
     *
     * @return The result of a successful output guardrail validation with a specific text.
     *
     * @param successfulText
     *            The text of the successful result.
     */
    /**
     * 生成包含指定成功文本的校验成功结果
     *
     * @param successfulText 成功结果附带的文本内容
     * @return 携带指定文本的输出护栏校验成功结果
     */
    default OutputGuardrailResult successWith(String successfulText) {
        return OutputGuardrailResult.successWith(successfulText);
    }

    /**
     * Produces a successful result with specific success text and result object
     *
     * @return The result of a successful output guardrail validation with a specific text.
     *
     * @param successfulText
     *            The text of the successful result.
     * @param successfulResult
     *            The object generated by this successful result.
     */
    /**
     * 生成包含指定成功文本与成功结果对象的成功结果
     *
     * @param successfulText 成功结果附带的文本内容
     * @param successfulResult 由当前成功结果生成的对象
     * @return 携带指定文本与结果对象的输出护栏校验成功结果
     */
    default OutputGuardrailResult successWith(String successfulText, Object successfulResult) {
        return OutputGuardrailResult.successWith(successfulText, successfulResult);
    }

    /**
     * Produces a successful result with specific success text
     *
     * @return The result of a successful output guardrail validation with a specific AiMessage.
     *
     * @param successfulAiMessage
     *            The AiMessage successful result.
     */
    /**
     * 生成包含指定 AI 消息的校验成功结果
     *
     * @param successfulAiMessage 表示成功结果的 AI 消息
     * @return 携带指定 AI 消息的输出护栏校验成功结果
     */
    default OutputGuardrailResult successWith(AiMessage successfulAiMessage) {
        return OutputGuardrailResult.successWith(successfulAiMessage);
    }

    /**
     * Produces a successful result with specific AiMessage and result object
     *
     * @param successfulAiMessage
     *            The AiMessage successful result.
     * @param successfulResult
     *            The object generated by this successful result.
     * @return The result of a successful output guardrail validation with a specific AiMessage.
     */
    /**
     * 生成包含指定 AI 消息和成功结果对象的校验成功结果
     *
     * @param successfulAiMessage 表示成功结果的 AI 消息
     * @param successfulResult 由当前成功结果生成的对象
     * @return 携带指定 AI 消息的输出护栏校验成功结果
     */
    default OutputGuardrailResult successWith(AiMessage successfulAiMessage, Object successfulResult) {
        return OutputGuardrailResult.successWith(successfulAiMessage, successfulResult);
    }

    /**
     * Produces a non-fatal failure
     *
     * @param message
     *            A message describing the failure.
     *
     * @return The result of a failed output guardrail validation.
     */
    /**
     * 生成一个非致命性的失败结果
     *
     * @param message 描述失败原因的信息
     * @return 输出护栏校验失败的结果
     */
    default OutputGuardrailResult failure(String message) {
        return new OutputGuardrailResult(new OutputGuardrailResult.Failure(message), false);
    }

    /**
     * Produces a non-fatal failure
     *
     * @param message
     *            A message describing the failure.
     * @param cause
     *            The exception that caused this failure.
     *
     * @return The result of a failed output guardrail validation.
     */
    /**
     * 生成一个非致命性的失败结果
     *
     * @param message 描述失败原因的信息
     * @param cause   导致此次失败的异常
     * @return 输出护栏校验失败的结果
     */
    default OutputGuardrailResult failure(String message, Throwable cause) {
        return new OutputGuardrailResult(new OutputGuardrailResult.Failure(message, cause), false);
    }

    /**
     * Produces a fatal failure
     *
     * @param message
     *            A message describing the failure.
     *
     * @return The result of a fatally failed output guardrail validation, blocking the evaluation of any other
     *         subsequent validation.
     */
    /**
     * 生成一个致命性失败结果
     *
     * @param message 描述失败原因的信息
     * @return 输出护栏校验致命失败的结果，会阻止后续任何其他校验逻辑的执行
     */
    default OutputGuardrailResult fatal(String message) {
        return new OutputGuardrailResult(Arrays.asList(new OutputGuardrailResult.Failure(message)), true);
    }

    /**
     * Produces a fatal failure
     *
     * @param message
     *            A message describing the failure.
     * @param cause
     *            The exception that caused this failure.
     *
     * @return The result of a fatally failed output guardrail validation, blocking the evaluation of any other
     *         subsequent validation.
     */
    /**
     * 生成一个致命性失败结果
     *
     * @param message 描述失败原因的信息
     * @param cause   导致此次失败的异常
     * @return 输出护栏校验致命失败的结果，会阻止后续任何其他校验逻辑的执行
     */
    default OutputGuardrailResult fatal(String message, Throwable cause) {
        return new OutputGuardrailResult(Arrays.asList(new OutputGuardrailResult.Failure(message, cause)), true);
    }

    /**
     * @param message
     *            A message describing the failure.
     *
     * @return The result of a fatally failed output guardrail validation, blocking the evaluation of any other
     *         subsequent validation and triggering a retry with the same user prompt.
     */
    /**
     * 生成一个致命性失败结果
     *
     * @param message 描述失败原因的信息
     * @return 输出护栏校验致命失败的结果，会阻止后续任何其他校验逻辑的执行，
     *         并使用相同的用户提示词触发重试
     */
    default OutputGuardrailResult retry(String message) {
        return new OutputGuardrailResult(Arrays.asList(new OutputGuardrailResult.Failure(message, null, true)), true);
    }

    /**
     * @param message
     *            A message describing the failure.
     * @param cause
     *            The exception that caused this failure.
     *
     * @return The result of a fatally failed output guardrail validation, blocking the evaluation of any other
     *         subsequent validation and triggering a retry with the same user prompt.
     */
    /**
     * 生成一个致命性失败结果
     *
     * @param message 描述失败原因的信息
     * @param cause   导致此次失败的异常
     * @return 输出护栏校验致命失败的结果，会阻止后续任何其他校验逻辑的执行，
     *         并使用相同的用户提示词触发重试
     */
    default OutputGuardrailResult retry(String message, Throwable cause) {
        return new OutputGuardrailResult(Arrays.asList(new OutputGuardrailResult.Failure(message, cause, true)), true);
    }

    /**
     * @param message
     *            A message describing the failure.
     * @param reprompt
     *            The new prompt to be used for the retry.
     *
     * @return The result of a fatally failed output guardrail validation, blocking the evaluation of any other
     *         subsequent validation and triggering a retry with a new user prompt.
     */
    /**
     * 生成一个致命性失败结果
     *
     * @param message 描述失败原因的信息
     * @param reprompt 用于重试的新提示词
     * @return 输出护栏校验致命失败的结果，会阻止后续任何其他校验逻辑的执行，
     *         并使用新的用户提示词触发重试
     */
    default OutputGuardrailResult reprompt(String message, String reprompt) {
        return new OutputGuardrailResult(
                Arrays.asList(new OutputGuardrailResult.Failure(message, null, true, reprompt)), true);
    }

    /**
     * @param message
     *            A message describing the failure.
     * @param cause
     *            The exception that caused this failure.
     * @param reprompt
     *            The new prompt to be used for the retry.
     *
     * @return The result of a fatally failed output guardrail validation, blocking the evaluation of any other
     *         subsequent validation and triggering a retry with a new user prompt.
     */
    /**
     * 生成一个致命性失败结果
     *
     * @param message 描述失败原因的信息
     * @param cause   导致此次失败的异常
     * @param reprompt 用于重试的新提示词
     * @return 输出护栏校验致命失败的结果，会阻止后续任何其他校验逻辑的执行，
     *         并使用新的用户提示词触发重试
     */
    default OutputGuardrailResult reprompt(String message, Throwable cause, String reprompt) {
        return new OutputGuardrailResult(
                Arrays.asList(new OutputGuardrailResult.Failure(message, cause, true, reprompt)), true);
    }

    /**
     * Produces a non-fatal failure and requests removal of the violating {@link dev.langchain4j.data.message.AiMessage}
     * from chat memory after the guardrail chain finishes.
     * This prevents the failed response from polluting future conversations.
     *
     * @param message A message describing the failure.
     * @return The result of a failed output guardrail validation with memory cleanup requested.
     */
    default OutputGuardrailResult failureWithMessageRemoval(String message) {
        return OutputGuardrailResult.failureWithMessageRemoval(message);
    }

    /**
     * Produces a non-fatal failure and requests removal of the violating {@link dev.langchain4j.data.message.AiMessage}
     * from chat memory after the guardrail chain finishes.
     * This prevents the failed response from polluting future conversations.
     *
     * @param message A message describing the failure.
     * @param cause   The exception that caused this failure.
     * @return The result of a failed output guardrail validation with memory cleanup requested.
     */
    default OutputGuardrailResult failureWithMessageRemoval(String message, Throwable cause) {
        return OutputGuardrailResult.failureWithMessageRemoval(message, cause);
    }

    /**
     * Produces a fatal failure and requests removal of the violating {@link dev.langchain4j.data.message.AiMessage}
     * from chat memory after the guardrail chain finishes.
     * This prevents the failed response from polluting future conversations.
     *
     * @param message A message describing the failure.
     * @return The result of a fatally failed output guardrail validation with memory cleanup requested.
     */
    default OutputGuardrailResult fatalWithMessageRemoval(String message) {
        return OutputGuardrailResult.fatalWithMessageRemoval(message);
    }

    /**
     * Produces a fatal failure and requests removal of the violating {@link dev.langchain4j.data.message.AiMessage}
     * from chat memory after the guardrail chain finishes.
     * This prevents the failed response from polluting future conversations.
     *
     * @param message A message describing the failure.
     * @param cause   The exception that caused this failure.
     * @return The result of a fatally failed output guardrail validation with memory cleanup requested.
     */
    default OutputGuardrailResult fatalWithMessageRemoval(String message, Throwable cause) {
        return OutputGuardrailResult.fatalWithMessageRemoval(message, cause);
    }
}
