package dev.langchain4j.classification;

import static dev.langchain4j.internal.ValidationUtils.ensureBetween;
import static dev.langchain4j.internal.ValidationUtils.ensureGreaterThanZero;
import static dev.langchain4j.internal.ValidationUtils.ensureNotBlank;
import static dev.langchain4j.internal.ValidationUtils.ensureNotEmpty;
import static dev.langchain4j.internal.ValidationUtils.ensureNotNull;
import static java.util.Comparator.comparingDouble;
import static java.util.stream.Collectors.toList;

import dev.langchain4j.data.embedding.Embedding;
import dev.langchain4j.data.segment.TextSegment;
import dev.langchain4j.model.embedding.EmbeddingModel;
import dev.langchain4j.store.embedding.CosineSimilarity;
import dev.langchain4j.store.embedding.RelevanceScore;
import java.util.ArrayList;
import java.util.Collection;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * A {@link TextClassifier} that uses an {@link EmbeddingModel} and predefined examples to perform classification.
 * Classification is performed by computing the similarity between the input text's embedding and the embeddings of labeled example texts.
 * The classification quality improves with a greater number of examples for each label.
 * Examples can be easily generated with the help of an LLM.
 * <p>
 * Example:
 * <pre>{@code
 * enum Sentiment {
 *     POSITIVE, NEUTRAL, NEGATIVE
 * }
 *
 *  Map<Sentiment, List<String>> examples = Map.of(
 *     POSITIVE, List.of("This is great!", "Wow, awesome!"),
 *     NEUTRAL,  List.of("Well, it's fine", "It's ok"),
 *     NEGATIVE, List.of("It is pretty bad", "Worst experience ever!")
 * );
 *
 * EmbeddingModel embeddingModel = new AllMiniLmL6V2QuantizedEmbeddingModel();
 *
 * TextClassifier<Sentiment> classifier = new EmbeddingModelTextClassifier<>(embeddingModel, examples);
 *
 * List<Sentiment> sentiments = classifier.classify("Awesome!");
 * System.out.println(sentiments); // [POSITIVE]
 * }</pre>
 *
 * @param <L> The type of the label (e.g., String, Enum, etc.)
 */
/**
 * 一种使用 {@link EmbeddingModel}（嵌入模型）和预定义示例来执行分类的 {@link TextClassifier}（文本分类器）。
 * 分类逻辑：通过计算输入文本的嵌入向量与带标签示例文本的嵌入向量之间的相似度完成分类。
 * 每个标签对应的示例数量越多，分类效果越好。
 * 可借助大语言模型（LLM）轻松生成示例数据。
 * <p>
 * 示例：
 * <pre>{@code
 * enum Sentiment {
 *     POSITIVE, NEUTRAL, NEGATIVE  // 积极、中性、消极
 * }
 *
 *  Map<Sentiment, List<String>> examples = Map.of(
 *     POSITIVE, List.of("太棒了！", "哇，太赞了！"),
 *     NEUTRAL,  List.of("嗯，还可以", "还行吧"),
 *     NEGATIVE, List.of("这太差劲了", "最糟糕的体验！")
 * );
 *
 * EmbeddingModel embeddingModel = new AllMiniLmL6V2QuantizedEmbeddingModel();
 *
 * TextClassifier<Sentiment> classifier = new EmbeddingModelTextClassifier<>(embeddingModel, examples);
 *
 * List<Sentiment> sentiments = classifier.classify("太棒了！");
 * System.out.println(sentiments); // [POSITIVE]
 * }</pre>
 *
 * @param <L> 标签的类型（例如：字符串、枚举等）
 */
public class EmbeddingModelTextClassifier<L> implements TextClassifier<L> {

    private final EmbeddingModel embeddingModel;
    private final Map<L, List<Embedding>> exampleEmbeddingsByLabel;
    private final int maxResults;
    private final double minScore;
    private final double meanToMaxScoreRatio;

    /**
     * Creates a classifier with the default values for {@link #maxResults} (1), {@link #minScore} (0)
     * and {@link #meanToMaxScoreRatio} (0.5).
     *
     * @param embeddingModel  The embedding model used for embedding both the examples and the text to be classified.
     * @param examplesByLabel A map containing examples of texts for each label.
     *                        The more examples, the better. Examples can be easily generated by the LLM.
     */
    public EmbeddingModelTextClassifier(
            EmbeddingModel embeddingModel, Map<L, ? extends Collection<String>> examplesByLabel) {
        this(embeddingModel, examplesByLabel, 1, 0, 0.5);
    }

    /**
     * Creates a classifier.
     *
     * @param embeddingModel      The embedding model used for embedding both the examples and the text to be classified.
     * @param examplesByLabel     A map containing examples of texts for each label.
     *                            Providing more examples per label generally improves classification accuracy.
     *                            Examples can be easily generated by the LLM.
     * @param maxResults          The maximum number of labels to return for each classification.
     * @param minScore            The minimum similarity score required for classification, in the range [0..1].
     *                            Labels scoring lower than this value will be discarded.
     * @param meanToMaxScoreRatio A ratio, in the range [0..1], between the mean and max scores used for calculating
     *                            the final score.
     *                            During classification, the embeddings of examples for each label are compared to
     *                            the embedding of the text being classified.
     *                            This results in two metrics: the mean and max scores.
     *                            The mean score is the average similarity score for all examples associated with a given label.
     *                            The max score is the highest similarity score, corresponding to the example most
     *                            similar to the text being classified.
     *                            A value of 0 means that only the mean score will be used for ranking labels.
     *                            A value of 0.5 means that both scores will contribute equally to the final score.
     *                            A value of 1 means that only the max score will be used for ranking labels.
     */
    /**
     * 创建一个分类器。
     *
     * @param embeddingModel      用于对示例文本和待分类文本进行嵌入处理的嵌入模型。
     * @param examplesByLabel     包含每个标签对应文本示例的映射表。
     *                            通常为每个标签提供更多示例能提高分类准确率。
     *                            示例文本可通过大语言模型（LLM）轻松生成。
     * @param maxResults          每次分类最多返回的标签数量。
     * @param minScore            分类所需的最低相似度分数，取值范围 [0..1]。
     *                            低于该分数的标签会被过滤掉。
     * @param meanToMaxScoreRatio 均值分数与最大值分数的权重比例，取值范围 [0..1]，用于计算最终得分。
     *                            分类过程中，会将每个标签下所有示例的嵌入向量与待分类文本的嵌入向量进行相似度对比，
     *                            得到两个指标：均值分数和最大值分数。
     *                            均值分数：与当前标签关联的所有示例的相似度平均值。
     *                            最大值分数：相似度最高的分数，对应与待分类文本最相似的示例。
     *                            取值为 0 时：仅使用均值分数对标签排序。
     *                            取值为 0.5 时：均值分数与最大值分数对最终得分的贡献相同。
     *                            取值为 1 时：仅使用最大值分数对标签排序。
     */
    public EmbeddingModelTextClassifier(
            EmbeddingModel embeddingModel,
            Map<L, ? extends Collection<String>> examplesByLabel,
            int maxResults,
            double minScore,
            double meanToMaxScoreRatio) {
        this.embeddingModel = ensureNotNull(embeddingModel, "embeddingModel");
        ensureNotEmpty(examplesByLabel, "examplesByLabel");
        this.maxResults = ensureGreaterThanZero(maxResults, "maxResults");
        this.minScore = ensureBetween(minScore, 0.0, 1.0, "minScore");
        this.meanToMaxScoreRatio = ensureBetween(meanToMaxScoreRatio, 0.0, 1.0, "meanToMaxScoreRatio");

        this.exampleEmbeddingsByLabel = new HashMap<>();
        examplesByLabel.forEach((label, examples) -> exampleEmbeddingsByLabel.put(
                label,
                embeddingModel
                        .embedAll(examples.stream().map(TextSegment::from).collect(toList()))
                        .content()));
    }

    @Override
    public ClassificationResult<L> classifyWithScores(String text) {
        ensureNotBlank(text, "text");

        Embedding textEmbedding = embeddingModel.embed(text).content();

        List<ScoredLabel<L>> scoredLabels = new ArrayList<>();
        exampleEmbeddingsByLabel.forEach((label, exampleEmbeddings) -> {
            double meanScore = 0;
            double maxScore = 0;
            for (Embedding exampleEmbedding : exampleEmbeddings) {
                double cosineSimilarity = CosineSimilarity.between(textEmbedding, exampleEmbedding);
                double score = RelevanceScore.fromCosineSimilarity(cosineSimilarity);
                meanScore += score;
                maxScore = Math.max(score, maxScore);
            }
            meanScore /= exampleEmbeddings.size();

            double aggregateScore = aggregatedScore(meanScore, maxScore);
            if (aggregateScore >= minScore) {
                scoredLabels.add(new ScoredLabel<>(label, aggregateScore));
            }
        });

        return new ClassificationResult<>(scoredLabels.stream()
                // sorting in descending order to return highest score first
                .sorted(comparingDouble(classificationResult -> 1 - classificationResult.score()))
                .limit(maxResults)
                .collect(toList()));
    }

    private double aggregatedScore(double meanScore, double maxScore) {
        return (meanToMaxScoreRatio * meanScore) + ((1 - meanToMaxScoreRatio) * maxScore);
    }
}
