package dev.langchain4j.service.tool.search;

import dev.langchain4j.Experimental;
import dev.langchain4j.agent.tool.ToolSpecification;
import dev.langchain4j.invocation.InvocationContext;

import java.util.List;

/**
 * Strategy for discovering tools dynamically by an LLM during an AI Service invocation.
 * LLM在AI服务调用期间动态发现工具的策略。
 * <p>
 * A {@code ToolSearchStrategy} allows reducing token usage by avoiding sending all available
 * tools to the LLM upfront. Instead, the LLM is initially exposed only to one or more
 * <em>tool search tools</em>, which it can call to discover relevant tools on demand.
 * <p>
 *     <p>
 *  *     ToolSearchStrategy通过避免提前向LLM发送所有可用工具来减少令牌使用。
 *  *     相反，LLM最初只接触一个或多个工具搜索工具，它可以根据需要调用这些工具来发现相关工具。
 *  * </p>
 * Once the LLM performs a tool search, the matching tools are included in subsequent
 * requests, typically accumulating until the corresponding search result message is evicted
 * from the chat memory.
 * <p>
 *     一旦LLM执行了工具搜索，匹配的工具就会包含在后续请求中，通常会累积，直到相应的搜索结果消息从聊天存储器中删除。
 * </p>
 *
 * <p>
 * LangChain4j provides out-of-the-box implementations such as
 * {@link dev.langchain4j.service.tool.search.simple.SimpleToolSearchStrategy}
 * and {@link dev.langchain4j.service.tool.search.vector.VectorToolSearchStrategy},
 * but custom strategies can be implemented to support alternative discovery mechanisms.
 *
 * @see dev.langchain4j.service.tool.search.simple.SimpleToolSearchStrategy
 * @see dev.langchain4j.service.tool.search.vector.VectorToolSearchStrategy
 * @since 1.12.0
 */
@Experimental
public interface ToolSearchStrategy {

    /**
     * Returns one or more tool specifications that are exposed to the LLM and are used to perform tool searches.
     * <p>
     *     返回一个或多个暴露给LLM并用于执行工具搜索的工具规范。
     * </p>
     *
     * @param invocationContext the AI Service invocation context
     * @return list containing one or more tool search tools
     */
    List<ToolSpecification> getToolSearchTools(InvocationContext invocationContext);

    /**
     * Executes a tool search request generated by the LLM and matching it against searchable tools.
     * <p>
     * 执行LLM生成的工具搜索请求，并将其与可搜索工具进行匹配。
     * </p>
     *
     * @param toolSearchRequest the tool search request
     * @return the search result containing matching tool names
     */
    ToolSearchResult search(ToolSearchRequest toolSearchRequest);
}
